# Generated by Django 5.0.1 on 2024-04-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='starting_price',
            new_name='starting_bit',
        ),
    ]
